apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthtart-boot-deploy
spec:
  selector:
    matchLabels:
      app: healthtart-boot
  replicas: 1
  template:
    metadata:
      labels:
        app: healthtart-boot
    spec:
      containers:
      - name: boot-container
        # image: ys0915/k8s_b_ing:latest
        # image: kyeongseok/nine_b_proj:latest
        image: kyeongseok/healthtart-boot:latest
        imagePullPolicy: Always
        ports:
        # - containerPort: 7777
        - containerPort: 8080

      - name: redis-container
        # Redis 컨테이너
        image: redis:latest
        ports:
        - containerPort: 6379