apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthtart-vue-deploy
spec:
  selector:
    matchLabels:
      app: healthtart-vue
  template:
    metadata:
      labels:
        app: healthtart-vue
    spec:
      containers:
      - name: vue-container
        # image: ys0915/k8s_v_ing:latest
        # image: kyeongseok/nine_v_proj:latest
        image: kyeongseok/healthtart-vue:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80      # 5173이 아니라 80으로 바꿔야 한다.