apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bWFyaWRi        # 'mariadb' base64
  MYSQL_DATABASE: aGVhbHRodGFydGRi    # 'healthtartdb' base64
  MYSQL_USER: aW50Ynl0ZQ==            # 'intbyte' base64
  MYSQL_PASSWORD: aW50Ynl0ZQ==        # 'intbyte' base64